"""Multi-language support for HablaPRO"""

LANGUAGES = {
    "es": {
        "name": "Español",
        "flag": "🇪🇸",
        "translations": {
            # Navigation and Header
            "app_title": "HablaPRO - Analizador de Habilidades de Presentación",
            "app_subtitle": "Mejora tus habilidades de presentación con análisis IA",
            "app_description": "Plataforma de análisis inteligente para mejorar habilidades de presentación mediante retroalimentación personalizada",
            "login": "Iniciar Sesión",
            "register": "Registrarse",
            "logout": "Cerrar Sesión",
            "dashboard": "Panel de Control",
            "settings": "Configuraciones",
            
            # User Management
            "teacher_info": "Información del Profesor",
            "student_info": "Información del Estudiante",
            "username": "Usuario",
            "password": "Contraseña",
            "full_name": "Nombre Completo",
            "institution": "Institución",
            "register_teacher": "Registrar Profesor",
            "register_student": "Registrar Estudiante",
            "student_dni": "DNI del Estudiante",
            "student_name": "Nombre del Estudiante (Opcional)",
            "anonymous_id": "ID Anónimo",
            "enter_username": "Ingresa tu usuario",
            "enter_password": "Ingresa tu contraseña",
            "choose_username": "Elige un nombre de usuario",
            "create_password": "Crea una contraseña",
            "enter_full_name": "Ingresa tu nombre completo",
            "enter_institution": "Ingresa tu institución",
            "create_account": "Crear Cuenta",
            "login_success": "Inicio de sesión exitoso",
            "account_created": "Cuenta creada exitosamente",
            "hello": "Hola",
            "dashboard_subtitle": "Bienvenido a HablaPRO",
            
            # Dashboard and Statistics
            "students": "Estudiantes", 
            "total_registered": "Total registrados",
            "active": "Activos",
            "this_month": "Este mes",
            "analyses": "Análisis",
            "videos_analyzed": "Videos analizados",
            "average": "Promedio",
            "class_general": "General de la clase",
            "no_data": "Sin datos",
            "score": "Puntuación",
            "start_first_class": "Comienza tu primera clase",
            "register_students_start": "Registra estudiantes para comenzar a usar HablaPRO",
            "enter_unique_id": "Ingresa un ID único",
            "full_name_optional": "Nombre completo (opcional)",
            "select_video": "Selecciona tu video de presentación",
            "video_help": "Sube un video de tu práctica de presentación para recibir feedback personalizado",
            "analyze_presentation": "Analizar Presentación",
            "processing_video": "Procesando video...",
            "analyzing_voice": "Analizando voz y prosodia...",
            "analyzing_body": "Analizando lenguaje corporal...",
            "analyzing_facial": "Analizando expresiones faciales...",
            "compiling_results": "Compilando resultados...",
            "analysis_complete": "¡Análisis completado!",
            
            # Content Analysis
            "upload_script": "Subir Guión (Opcional)",
            "script_help": "Sube el texto de tu presentación para análisis de contenido",
            "upload_rubric": "Subir Rúbrica (Opcional)",
            "rubric_help": "Sube la rúbrica de evaluación para criterios específicos",
            "content_analysis": "Análisis de Contenido",
            "rubric_evaluation": "Evaluación según Rúbrica",
            
            # Results
            "detailed_feedback": "Feedback Detallado",
            "charts": "Gráficos",
            "diagrams": "Diagramas",
            "overall_score": "Puntuación General",
            "voice_analysis": "Análisis de Voz y Prosodia",
            "body_analysis": "Análisis de Lenguaje Corporal",
            "facial_analysis": "Análisis de Expresiones Faciales",
            "voice_score": "Puntuación de Voz",
            "clarity": "Claridad",
            "speaking_rate": "Velocidad (ppm)",
            "filler_words": "Muletillas detectadas",
            "body_score": "Puntuación Corporal",
            "posture_stability": "Estabilidad de Postura",
            "gestures_detected": "Gestos Detectados",
            "general_movement": "Movimiento General",
            "facial_score": "Puntuación Facial",
            "eye_contact": "Contacto Visual",
            "average_confidence": "Confianza Promedio",
            "smiles_detected": "Sonrisas Detectadas",
            
            # Progress and History
            "historical_progress": "Progreso Histórico",
            "no_historical_data": "No hay datos históricos disponibles. ¡Sube tu primer video para comenzar!",
            "total_analyses": "Total de Análisis",
            "last_score": "Última Puntuación",
            "general_average": "Promedio General",
            "recent_improvement": "Mejora Reciente",
            
            # Export and Reports
            "export_pdf": "Exportar PDF",
            "export_excel": "Exportar Excel",
            "generate_report": "Generar Reporte",
            "individual_report": "Reporte Individual",
            "general_report": "Reporte General",
            "download_report": "Descargar Reporte",
            
            # Model Selection
            "model_version": "Versión del Modelo",
            "basic_model": "Modelo Básico",
            "advanced_model": "Modelo Avanzado",
            "basic_description": "Análisis de voz, lenguaje corporal y expresiones faciales",
            "advanced_description": "Incluye análisis de contenido, evaluación con rúbrica y reportes avanzados",
            
            # Settings
            "language_setting": "Idioma",
            "video_size_limit": "Límite de tamaño de video (MB)",
            "save_settings": "Guardar Configuraciones",
            "settings_saved": "Configuraciones guardadas exitosamente",
            
            # Messages
            "success": "Éxito",
            "error": "Error",
            "warning": "Advertencia",
            "info": "Información",
            "loading": "Cargando...",
            "please_wait": "Por favor espera...",
            "file_uploaded": "Archivo subido exitosamente",
            "analysis_error": "Error durante el análisis",
            "login_required": "Debes iniciar sesión para continuar",
            "insufficient_permissions": "Permisos insuficientes",
            
            # Feedback Messages
            "excellent_work": "¡Excelente trabajo!",
            "good_performance": "Buen desempeño general",
            "needs_improvement": "Necesitas trabajar en",
            "speaking_too_fast": "Hablas muy rápido",
            "speaking_too_slow": "Hablas muy lento",
            "good_speed": "Tu velocidad de habla es adecuada",
            "too_many_fillers": "Usas demasiadas muletillas",
            "good_clarity": "Tu claridad vocal es buena",
            "improve_posture": "Trabaja en mantener una postura más erguida",
            "good_eye_contact": "Mantuviste excelente contacto visual",
            "smile_more": "Sonríe más durante tu presentación",
            
            # Additional interface translations
            "welcome": "Bienvenido",
            "navigation": "Navegación",
            "video_analysis": "Análisis de Video",
            "student_management": "Gestión de Estudiantes",
            "reports": "Reportes",
            "fill_all_fields": "Completa todos los campos",
            "fill_required_fields": "Completa los campos requeridos",
            "analyzing_for": "Analizando para",
            "additional_content": "Contenido Adicional",
            "presentation_script": "Guión de Presentación",
            "no_script": "Sin guión",
            "type_script": "Escribir guión",
            "student_progress": "Progreso del Estudiante",
            "register_new_student": "Registrar Nuevo Estudiante",
            "register_student": "Registrar Estudiante",
            "dni_required": "DNI es requerido",
            "registered_students": "Estudiantes Registrados",
            "registration_date": "Fecha de Registro",
            "no_students_for_reports": "No hay estudiantes para generar reportes",
            "report_type": "Tipo de Reporte",
            "class_report": "Reporte de Clase",
            "select_student": "Seleccionar Estudiante",
            "generate_pdf": "Generar PDF",
            "download_pdf": "Descargar PDF",
            "generate_excel": "Generar Excel",
            "download_excel": "Descargar Excel",
            "report_generated": "Reporte generado",
            "no_analyses_for_student": "No hay análisis para este estudiante",
            "generate_class_pdf": "Generar PDF de Clase",
            "generate_class_excel": "Generar Excel de Clase",
            "no_analyses_for_class": "No hay análisis para la clase",
            "error_saving_settings": "Error al guardar configuraciones",
            "active_students": "Estudiantes Activos",
            "class_average": "Promedio de Clase",
            "recent_activity": "Actividad Reciente",
            "no_data_available": "No hay datos disponibles",
            "no_students_registered": "No hay estudiantes registrados",
            "register_students_first": "Registra estudiantes primero",
            "student": "Estudiante",
            "date": "Fecha",
            "name": "Nombre",
            "analyzing_content": "Analizando contenido...",
            "content_score": "Puntuación de Contenido",
            "progress_trend": "Tendencia de Progreso",
            
            # Advanced Results
            "advanced_results": "Resultados Avanzados",
            "simple_results": "Vista Simple",
            "analytics": "Analíticas",
            "recommendations": "Recomendaciones",
            "detailed_analytics": "Analíticas Detalladas",
            "performance_breakdown": "Desglose de Rendimiento",
            "comparison_metrics": "Métricas Comparativas",
            "detailed_metrics": "Métricas Detalladas",
            "aspect": "Aspecto",
            "status": "Estado",
            "voice_clarity": "Claridad de Voz",
            "speaking_pace": "Ritmo de Habla",
            "body_posture": "Postura Corporal",
            "pace_rating": "Evaluación de Ritmo",
            "overall": "General",
            "voice": "Voz",
            "body": "Corporal",
            "facial": "Facial",
            "personalized_recommendations": "Recomendaciones Personalizadas",
            "priority_improvements": "Mejoras Prioritarias",
            "strengths": "Fortalezas",
            "needs_attention": "Necesita Atención",
            "great_job": "Excelente Trabajo",
            "detailed_recommendations": "Recomendaciones Detalladas",
            "voice_improvement": "Trabaja en mejorar la claridad y el ritmo de tu voz",
            "body_improvement": "Enfócate en mantener mejor postura y gestos naturales",
            "facial_improvement": "Practica mantener contacto visual y expresiones naturales",
            "voice_strength": "Tu voz es clara y tu ritmo es apropiado",
            "body_strength": "Tu lenguaje corporal es confiado y profesional",
            "facial_strength": "Tienes excelente contacto visual y expresiones naturales",
            "excellent": "Excelente",
            "very_good": "Muy Bueno",
            "good": "Bueno",
            "needs_improvement": "Necesita Mejorar",
            "needs_work": "Necesita Trabajo",
            
            # Analysis Mode
            "analysis_mode": "Modo de Análisis",
            "simple_analysis": "Análisis Simple",
            "advanced_analysis": "Análisis Avanzado",
            "simple_analysis_description": "Análisis básico de habilidades de presentación física",
            "advanced_analysis_description": "Análisis completo incluyendo contenido de la presentación",
            "all_simple_features": "Todas las características del análisis simple",
            "script_comparison": "Comparación con guión",
            "select_analysis_mode": "Selecciona el modo de análisis",
            "optional": "Opcional",
            "script_help_detailed": "Sube o escribe el guión de tu presentación para comparar el contenido hablado con el planeado",
            "script_input_method": "Método de entrada del guión",
            "upload_script_file": "Subir archivo de guión",
            "write_script_manually": "Escribir guión manualmente",
            "supported_script_formats": "Formatos soportados",
            "only_txt_supported_now": "Solo archivos TXT están soportados por ahora",
            "error_reading_script": "Error al leer el guión",
            "write_your_script": "Escribe tu guión aquí",
            "script_placeholder": "Escribe el texto completo de tu presentación aquí...",
            "script_preview": "Vista previa del guión",
            "analyze_presentation_simple": "Analizar Presentación (Simple)",
            "analyze_presentation_advanced": "Analizar Presentación (Avanzado)",
            "content_analysis": "Análisis de Contenido",
            "script_adherence": "Adherencia al Guión",
            "content_quality": "Calidad del Contenido",
            "message_clarity": "Claridad del Mensaje",
            "content_score": "Puntuación de Contenido",
            "content": "Contenido",
            "score_comparison": "Comparación de Puntuaciones",
            "upload_video_presentation": "Sube el video de presentación",
            "supported_formats": "Formatos soportados",
            "go_to_students_tab": "Ve a la pestaña de estudiantes para registrar alumnos",
            "no_name": "Sin nombre",
            "analyzing_voice_prosody": "Analizando voz y prosodia",
            "analyzing_body_language": "Analizando lenguaje corporal",
            "analyzing_facial_expressions": "Analizando expresiones faciales",
            "video_processing_error": "Error procesando video",
            "processing_with_ai": "Procesando con inteligencia artificial",
            "analysis_completed_successfully": "Análisis completado exitosamente"
        }
    },
    "en": {
        "name": "English",
        "flag": "🇺🇸",
        "translations": {
            # Navigation and Header
            "app_title": "HablaPRO - Presentation Skills Analyzer",
            "app_subtitle": "Improve your presentation skills with AI analysis",
            "app_description": "Intelligent analysis platform to improve presentation skills through personalized feedback",
            "login": "Login",
            "register": "Register",
            "logout": "Logout",
            "dashboard": "Dashboard",
            "settings": "Settings",
            
            # User Management
            "teacher_info": "Teacher Information",
            "student_info": "Student Information",
            "username": "Username",
            "password": "Password",
            "full_name": "Full Name",
            "institution": "Institution",
            "register_teacher": "Register Teacher",
            "register_student": "Register Student",
            "student_dni": "Student ID",
            "student_name": "Student Name (Optional)",
            "anonymous_id": "Anonymous ID",
            "enter_username": "Enter your username",
            "enter_password": "Enter your password",
            "choose_username": "Choose a username",
            "create_password": "Create a password",
            "enter_full_name": "Enter your full name",
            "enter_institution": "Enter your institution",
            "create_account": "Create Account",
            "login_success": "Login successful",
            "account_created": "Account created successfully",
            "hello": "Hello",
            "dashboard_subtitle": "Welcome to HablaPRO",
            
            # Dashboard and Statistics
            "students": "Students", 
            "total_registered": "Total registered",
            "active": "Active",
            "this_month": "This month",
            "analyses": "Analyses",
            "videos_analyzed": "Videos analyzed",
            "average": "Average",
            "class_general": "Class general",
            "no_data": "No data",
            "score": "Score",
            "start_first_class": "Start your first class",
            "register_students_start": "Register students to start using HablaPRO",
            "enter_unique_id": "Enter a unique ID",
            "full_name_optional": "Full name (optional)",
            
            # Analysis Interface
            "upload_video": "Upload Practice Video",
            "select_video": "Select your presentation video",
            "video_help": "Upload a video of your presentation practice for personalized feedback",
            "analyze_presentation": "Analyze Presentation",
            "processing_video": "Processing video...",
            "analyzing_voice": "Analyzing voice and prosody...",
            "analyzing_body": "Analyzing body language...",
            "analyzing_facial": "Analyzing facial expressions...",
            "compiling_results": "Compiling results...",
            "analysis_complete": "Analysis completed!",
            
            # Content Analysis
            "upload_script": "Upload Script (Optional)",
            "script_help": "Upload your presentation text for content analysis",
            "upload_rubric": "Upload Rubric (Optional)",
            "rubric_help": "Upload evaluation rubric for specific criteria",
            "content_analysis": "Content Analysis",
            "rubric_evaluation": "Rubric-based Evaluation",
            
            # Results
            "detailed_feedback": "Detailed Feedback",
            "charts": "Charts",
            "diagrams": "Diagrams",
            "overall_score": "Overall Score",
            "voice_analysis": "Voice and Prosody Analysis",
            "body_analysis": "Body Language Analysis",
            "facial_analysis": "Facial Expression Analysis",
            "voice_score": "Voice Score",
            "clarity": "Clarity",
            "speaking_rate": "Speaking Rate (wpm)",
            "filler_words": "Filler words detected",
            "body_score": "Body Score",
            "posture_stability": "Posture Stability",
            "gestures_detected": "Gestures Detected",
            "general_movement": "General Movement",
            "facial_score": "Facial Score",
            "eye_contact": "Eye Contact",
            "average_confidence": "Average Confidence",
            "smiles_detected": "Smiles Detected",
            
            # Progress and History
            "historical_progress": "Historical Progress",
            "no_historical_data": "No historical data available. Upload your first video to get started!",
            "total_analyses": "Total Analyses",
            "last_score": "Last Score",
            "general_average": "General Average",
            "recent_improvement": "Recent Improvement",
            
            # Export and Reports
            "export_pdf": "Export PDF",
            "export_excel": "Export Excel",
            "generate_report": "Generate Report",
            "individual_report": "Individual Report",
            "general_report": "General Report",
            "download_report": "Download Report",
            
            # Model Selection
            "model_version": "Model Version",
            "basic_model": "Basic Model",
            "advanced_model": "Advanced Model",
            "basic_description": "Analysis of voice, body language and facial expressions",
            "advanced_description": "Includes content analysis, rubric evaluation and advanced reports",
            
            # Settings
            "language_setting": "Language",
            "video_size_limit": "Video size limit (MB)",
            "save_settings": "Save Settings",
            "settings_saved": "Settings saved successfully",
            
            # Messages
            "success": "Success",
            "error": "Error",
            "warning": "Warning",
            "info": "Information",
            "loading": "Loading...",
            "please_wait": "Please wait...",
            "file_uploaded": "File uploaded successfully",
            "analysis_error": "Error during analysis",
            "login_required": "You must log in to continue",
            "insufficient_permissions": "Insufficient permissions",
            
            # Feedback Messages
            "excellent_work": "Excellent work!",
            "good_performance": "Good overall performance",
            "needs_improvement": "You need to work on",
            "speaking_too_fast": "You speak too fast",
            "speaking_too_slow": "You speak too slow",
            "good_speed": "Your speaking speed is appropriate",
            "too_many_fillers": "You use too many filler words",
            "good_clarity": "Your vocal clarity is good",
            "improve_posture": "Work on maintaining better posture",
            "good_eye_contact": "You maintained excellent eye contact",
            "smile_more": "Smile more during your presentation",
            
            # Advanced Results
            "advanced_results": "Advanced Results",
            "simple_results": "Simple View",
            "analytics": "Analytics",
            "recommendations": "Recommendations",
            "detailed_analytics": "Detailed Analytics",
            "performance_breakdown": "Performance Breakdown",
            "comparison_metrics": "Comparison Metrics",
            "detailed_metrics": "Detailed Metrics",
            "aspect": "Aspect",
            "status": "Status",
            "voice_clarity": "Voice Clarity",
            "speaking_pace": "Speaking Pace",
            "body_posture": "Body Posture",
            "pace_rating": "Pace Rating",
            "overall": "Overall",
            "voice": "Voice",
            "body": "Body",
            "facial": "Facial",
            "personalized_recommendations": "Personalized Recommendations",
            "priority_improvements": "Priority Improvements",
            "strengths": "Strengths",
            "needs_attention": "Needs Attention",
            "great_job": "Great Job",
            "detailed_recommendations": "Detailed Recommendations",
            "voice_improvement": "Work on improving voice clarity and pace",
            "body_improvement": "Focus on maintaining better posture and natural gestures",
            "facial_improvement": "Practice maintaining eye contact and natural expressions",
            "voice_strength": "Your voice is clear with appropriate pace",
            "body_strength": "Your body language is confident and professional",
            "facial_strength": "You have excellent eye contact and natural expressions",
            "excellent": "Excellent",
            "very_good": "Very Good",
            "good": "Good",
            "needs_improvement": "Needs Improvement",
            "needs_work": "Needs Work",
            
            # Analysis Mode
            "analysis_mode": "Analysis Mode",
            "simple_analysis": "Simple Analysis",
            "advanced_analysis": "Advanced Analysis",
            "simple_analysis_description": "Basic analysis of physical presentation skills",
            "advanced_analysis_description": "Complete analysis including presentation content",
            "all_simple_features": "All simple analysis features",
            "script_comparison": "Script comparison",
            "select_analysis_mode": "Select analysis mode",
            "optional": "Optional",
            "script_help_detailed": "Upload or write your presentation script to compare spoken content with planned content",
            "script_input_method": "Script input method",
            "upload_script_file": "Upload script file",
            "write_script_manually": "Write script manually",
            "supported_script_formats": "Supported formats",
            "only_txt_supported_now": "Only TXT files are supported for now",
            "error_reading_script": "Error reading script",
            "write_your_script": "Write your script here",
            "script_placeholder": "Write the complete text of your presentation here...",
            "script_preview": "Script preview",
            "analyze_presentation_simple": "Analyze Presentation (Simple)",
            "analyze_presentation_advanced": "Analyze Presentation (Advanced)",
            "content_analysis": "Content Analysis",
            "script_adherence": "Script Adherence",
            "content_quality": "Content Quality",
            "message_clarity": "Message Clarity",
            "content_score": "Content Score",
            "content": "Content",
            "score_comparison": "Score Comparison",
            "upload_video_presentation": "Upload presentation video",
            "supported_formats": "Supported formats",
            "go_to_students_tab": "Go to students tab to register students",
            "no_name": "No name",
            "analyzing_voice_prosody": "Analyzing voice and prosody",
            "analyzing_body_language": "Analyzing body language",
            "analyzing_facial_expressions": "Analyzing facial expressions",
            "video_processing_error": "Video processing error",
            "processing_with_ai": "Processing with artificial intelligence",
            "analysis_completed_successfully": "Analysis completed successfully"
        }
    },
    "qu": {
        "name": "Quechua",
        "flag": "🏔️",
        "translations": {
            # Navigation and Header
            "app_title": "HablaPRO - Rimana Yachaykunata Qhawaq",
            "app_subtitle": "Rimana yachayniykita allinchaspa AI qhawaywan",
            "login": "Yaykuy",
            "register": "Qillqakuy",
            "logout": "Lluqsiy",
            "dashboard": "Kamachiy Panel",
            "settings": "Churaykunapaq",
            
            # User Management
            "teacher_info": "Yachachiqpa Willakuynin",
            "student_info": "Yachaqpa Willakuynin",
            "username": "Ruraqpa Sutin",
            "password": "Yaykuna Rima",
            "full_name": "Hunt'a Suti",
            "institution": "Yachana Wasi",
            "register_teacher": "Yachachiqta Qillqakuy",
            "register_student": "Yachaqta Qillqakuy",
            "student_dni": "Yachaqpa DNI",
            "student_name": "Yachaqpa Sutin (Akllanalla)",
            "anonymous_id": "Pakana ID",
            
            # Analysis Interface
            "upload_video": "Ruraykuna Videota Wichay",
            "select_video": "Rimayniykipa videonta akllay",
            "video_help": "Rimayniykipa ruraykuna videonta wichay allin yanapaykuna chaskinapaq",
            "analyze_presentation": "Rimayta Qhaway",
            "processing_video": "Videota ruraspa...",
            "analyzing_voice": "Kunkata hinaspa takita qhawaspa...",
            "analyzing_body": "Kurku rimayta qhawaspa...",
            "analyzing_facial": "Uyapa rimakunata qhawaspa...",
            "compiling_results": "Ruwaykunata huñuspa...",
            "analysis_complete": "¡Qhaway tukusqa!",
            
            # Content Analysis
            "upload_script": "Qillqata Wichay (Akllanalla)",
            "script_help": "Rimayniykipa qillqanta wichay contenidota qhawanapaq",
            "upload_rubric": "Chaninchayta Wichay (Akllanalla)",
            "rubric_help": "Chaninchaypaq kamachiykunata wichay",
            "content_analysis": "Contenido Qhaway",
            "rubric_evaluation": "Rúbrica nisqanman hina Chaninchaykuy",
            
            # Results
            "detailed_feedback": "Sut'i Yanapaykuna",
            "charts": "Qillqakuna",
            "diagrams": "Rikuchiykunapaq",
            "overall_score": "Tukuypaq Puntuacion",
            "voice_analysis": "Kunka hinaspa Taki Qhaway",
            "body_analysis": "Kurku Rimay Qhaway",
            "facial_analysis": "Uya Rimaykunapa Qhawaynin",
            "voice_score": "Kunka Puntuacion",
            "clarity": "Sut'inchaykuy",
            "speaking_rate": "Rimay Usqhay (ppm)",
            "filler_words": "Hunt'asqa rimakuna tarisqa",
            "body_score": "Kurku Puntuacion",
            "posture_stability": "Sayasqapa Takyay",
            "gestures_detected": "Sañakuna Tarisqa",
            "general_movement": "Llapanpaq Kuyuy",
            "facial_score": "Uya Puntuacion",
            "eye_contact": "Ñawi Tupanakuy",
            "average_confidence": "Chawpi Confianza",
            "smiles_detected": "Asikuna Tarisqa",
            
            # Progress and History
            "historical_progress": "Ñawpaq Ñanpi Puriy",
            "no_historical_data": "Mana ñawpaq willaykuna kanchu. ¡Ñawpaq videota wichay qallariyniykipaq!",
            "total_analyses": "Tukuy Qhawaykunapaq",
            "last_score": "Qhipa Puntuacion",
            "general_average": "Llapanpaq Chawpi",
            "recent_improvement": "Kunan Allinchaykuy",
            
            # Export and Reports
            "export_pdf": "PDF Lluqsichiy",
            "export_excel": "Excel Lluqsichiy",
            "generate_report": "Willakuyta Ruray",
            "individual_report": "Sapanka Willakuy",
            "general_report": "Llapanpaq Willakuy",
            "download_report": "Willakuyta Urquy",
            
            # Model Selection
            "model_version": "Modelo Rikuy",
            "basic_model": "Hatun Modelo",
            "advanced_model": "Ñawpaqman Puriq Modelo",
            "basic_description": "Kunka, kurku rimay hinaspa uya rimakunapa qhawaynin",
            "advanced_description": "Contenido qhaway, rúbrica chaninchaykuy hinaspa ñawpaqman puriq willakuykunayuq",
            
            # Settings
            "language_setting": "Rimay",
            "video_size_limit": "Video hatunkaynin limitasqa (MB)",
            "save_settings": "Churaykunata Waqaychay",
            "settings_saved": "Churaykunaqa allinta waqaychasqa",
            
            # Messages
            "success": "Allin Ruway",
            "error": "Pantay",
            "warning": "Yuyaychay",
            "info": "Willay",
            "loading": "Kargaspa...",
            "please_wait": "Ama hina kaspa suyay...",
            "file_uploaded": "Archivo allinta wichasqa",
            "analysis_error": "Qhawaypi pantay",
            "login_required": "Yaykuy tiyan purinapaq",
            "insufficient_permissions": "Mana allin atiykuna",
            
            # Feedback Messages
            "excellent_work": "¡Ancha allin ruway!",
            "good_performance": "Allin llapan ruway",
            "needs_improvement": "Llamkay tiyan",
            "speaking_too_fast": "Ancha usqhaylla rimanki",
            "speaking_too_slow": "Ancha pisi rimaylla rimanki",
            "good_speed": "Rimayniykipa usqhayninqa allin",
            "too_many_fillers": "Ancha achka hunt'ana rimakunata llamkanki",
            "good_clarity": "Kunkaykipa sut'inchaynin allin",
            "improve_posture": "Aswan allin sayasqata llamkay",
            "good_eye_contact": "Ancha allin ñawi tupanakuyta ruwarqanki",
            "smile_more": "Aswan achka asikapuy rimayniykipi"
        }
    }
}

def get_text(key, language="es"):
    """Get translated text for given key and language"""
    return LANGUAGES.get(language, LANGUAGES["es"])["translations"].get(key, key)

def get_available_languages():
    """Get list of available languages"""
    return [(code, lang["name"], lang["flag"]) for code, lang in LANGUAGES.items()]