[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 300

[theme]
base = "light"
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"

[browser]
gatherUsageStats = false